/* English content for nexgen.bh.
 *
 * Mirrors the exact key structure of ar-content.js so a single locale-aware
 * builder renders both. Every string here is the string the site ships today —
 * this file only moves them out of the templates so the two locales share one
 * set of markup.
 *
 * `names` holds Arabic renderings of personal names, used only by the Arabic
 * locale. They are standard MSA spellings and should be confirmed by the owner.
 */

module.exports = {
  lang: 'en',
  dir: 'ltr',
  ogLocale: 'en_US',

  nav: {
    home: 'Home',
    about: 'About Us',
    ventures: 'Ventures &amp; Partnerships',
    contact: 'Contact',
    openMenu: (label) => `Open ${label} menu`,
    openNav: 'Open navigation menu',
    skip: 'Skip to content',
    brandHome: 'NEXGEN Holdings — Home',
    brandName: 'NEXGEN Holdings logo',
    primary: 'Primary',
    langLabel: 'العربية',
    langAria: 'Switch to Arabic',
  },

  footer: {
    blurb: 'A Gulf-based holding company building and scaling high-impact ventures across renewable &amp; clean energy, digital transformation, and artificial intelligence.',
    ventures: 'Ventures &amp; Partnerships',
    quick: 'Quick Links',
    getInTouch: 'Get in touch',
    home: 'Home',
    about: 'About Us',
    venturesLink: 'Ventures &amp; Partnerships',
    contact: 'Contact Us',
    phone: 'Phone',
    email: 'Email',
    linkedin: 'LinkedIn',
    sitemap: 'Sitemap',
    copyright: `© Copyright ${new Date().getFullYear()} NEXGEN Holdings`,
    venturesAria: 'Ventures & Partnerships',
    quickAria: 'Quick Links',
  },

  cta: {
    alt: (phone) => `or call ${phone}`,
  },

  ventures: {
    'trust-flow': {
      kicker: 'Corporate &amp; Investor Onboarding AI',
      copy: 'A platform that accelerates onboarding for banks, investment firms, asset managers, &amp; funds through AI-driven document processing, automated KYC/KYB, &amp; intelligent compliance summaries.',
    },
    esaal: {
      kicker: 'Digital Receipts &amp; Spending Intelligence',
      copy: 'An AI engine that converts receipts into structured, searchable financial data—powering insights for individuals, businesses, and retailers.',
    },
    dari: {
      kicker: 'AI-Powered Smart Living System',
      copy: 'A next-generation smart home and building platform that adapts to behavior, emotion, and daily routines—not just device commands.',
    },
    saby: {
      kicker: 'Modern Technology Studio',
      copy: 'NEXGEN’s dedicated software engineering arm specializing in AI development, digital transformation, and enterprise-grade platforms.',
    },
    inpipe: {
      kicker: 'HydroXS In-Pipe Hydropower',
      copy: 'NEXGEN is the exclusive regional partner of InPipe Energy (USA), bringing HydroXS® technology to the Gulf—turning excess water pressure inside pipelines into clean electricity.',
    },
  },

  pillars: {
    energy: {
      name: 'Renewable &amp; Clean Energy',
      blurb: 'Turning the energy already inside water infrastructure into clean, reliable power.',
    },
    digital: {
      name: 'Digital Transformation',
      blurb: 'Replacing paper, manual work, and fragmented systems with connected digital platforms.',
    },
    ai: {
      name: 'Artificial Intelligence',
      blurb: 'Applying AI to documents, decisions, and daily life—from institutional compliance to smart homes.',
    },
  },

  ui: {
    readMore: 'Read More',
    inDevelopment: 'In development — coming soon',
  },

  pages: {
    index: {
      title: 'NEXGEN Holdings — Renewable Energy, Digital Transformation & AI in the GCC',
      desc: 'NEXGEN Holdings is a Gulf-based holding company building high-impact ventures in renewable & clean energy, digital transformation, and artificial intelligence across the GCC.',
      heroTitle: 'Building the Next Generation of <span class="nowrap">Impact-Driven</span> Ventures',
      heroLead: 'A Gulf-based holding company building and scaling high-impact ventures in renewable &amp; clean energy, digital transformation, and artificial intelligence—for governments, utilities, banks, and enterprises across the GCC.',
      heroBtn1: 'Explore Our Focus Areas',
      heroBtn2: 'Explore Our Ventures',
      h2: 'Innovation With Purpose. Impact With Scale.',
      lead: 'NEXGEN is a diversified holding company headquartered in the Gulf, focused on building ventures that deliver economic, environmental, and digital transformation.',
      p1: 'Our portfolio spans three focus areas—renewable &amp; clean energy, digital transformation, and artificial intelligence—each designed to solve real challenges and create real value.',
      p2: 'We partner with global technology leaders, regional institutions, and forward-thinking organizations to bring world-class solutions to the GCC.',
      btn: 'Learn More',
      eyebrow: 'Our focus',
      focusH2: 'Three Focus Areas',
      focusLead: 'Every NEXGEN company is built within one of three areas.',
      ctaTitle: 'Let’s build the future together.',
      ctaText: 'Ready to explore partnership opportunities in renewable energy, digital transformation, or AI?',
      ctaLabel: 'Contact Us',
    },

    about: {
      title: 'About Us — NEXGEN Holdings',
      desc: 'NEXGEN Holdings builds and scales ventures across renewable & clean energy, digital transformation, and artificial intelligence — our vision, mission, values, and leadership.',
      heroTitle: 'About NEXGEN Holdings',
      heroLead: 'A holding company headquartered in Bahrain, building and scaling high-impact ventures across renewable &amp; clean energy, digital transformation, and artificial intelligence, active across the GCC.',
      h2: 'Building the Next Generation of <span class="nowrap">Impact-Driven</span> Ventures',
      lead: 'NEXGEN Holdings is a diversified holding company headquartered in Bahrain, focused on creating, scaling, and operating ventures across the GCC that deliver measurable economic, environmental, and technological impact.',
      p1: 'We operate across three focus areas—renewable &amp; clean energy, digital transformation, and artificial intelligence—transforming proven ideas into structured, market-ready businesses. NEXGEN combines strategic vision, regional insight, and disciplined execution to ensure every venture is built for long-term relevance and sustainable growth.',
      p2: 'Rather than pursuing volume, NEXGEN follows a selective, high-conviction approach—focusing on ventures that align with regional priorities, regulatory environments, and real market demand across the GCC.',
      visionH: 'Our Vision',
      visionP: 'To become the Gulf’s leading innovation holding—driving the transition toward sustainable energy, digital transformation, and AI-enabled ecosystems.',
      missionH: 'Our Mission',
      missionP: 'To build and scale ventures that solve real-world challenges, reduce environmental impact, improve operational efficiency, and enable long-term value creation for governments, enterprises, and communities across the region.',
      valuesEyebrow: 'Our values',
      valuesH2: 'How We Work',
      values: ['Innovation', 'Sustainability', 'Integrity', 'Partnership', 'Excellence', 'Impact'],
      vmH2: 'Our Vision &amp; Mission',
      founderEyebrow: 'Founder’s message',
      founderName: 'Abdullah Sultan AlMutairi',
      founderRole: 'Chairman &amp; CEO',
      founderP1: 'NEXGEN was founded on the belief that innovation must deliver real value—not just ideas.',
      founderP2: 'As a holding company, our role goes beyond capital allocation. We actively shape ventures that address critical challenges facing our region, from clean energy and infrastructure efficiency to financial systems and digital transformation.',
      founderP3: 'We take a disciplined and selective approach, partnering with proven global innovators and regional institutions to ensure each venture is practical, scalable, and aligned with the long-term priorities of the Gulf.',
      founderP4: 'NEXGEN is committed to building companies that stand the test of time—creating sustainable impact for our partners, our markets, and future generations.',
      leadershipEyebrow: 'Leadership',
      leadershipH2: 'Our Leadership Structure',
      advisorsH2: 'Advisory Board',
      partnershipsEyebrow: 'Partnerships',
      partnershipsH2: 'Strategic Partnerships &amp; Investment Interest',
      partnershipsP1: 'NEXGEN selectively engages with strategic partners, institutional investors, and family offices that share our vision for sustainable growth and high-impact innovation across renewable energy, digital transformation, and AI.',
      partnershipsP2: 'We do not pursue open fundraising or public investment offerings. All partnership and investment discussions are evaluated privately and aligned with NEXGEN’s strategic roadmap, governance standards, and long-term objectives.',
      partnershipsP3: 'Organizations interested in exploring strategic alignment with NEXGEN are invited to submit a confidential inquiry.',
      partnershipsBtn: 'Express Strategic Interest',
      forwardH2: 'Looking Forward',
      forwardP: 'NEXGEN continues to expand its portfolio with future ventures aligned with renewable energy, digital transformation, and AI. Our platform is designed to evolve—welcoming new opportunities that strengthen the NEXGEN ecosystem while preserving focus, quality, and strategic intent.',
      partnerH3: 'Partner With NEXGEN',
      partnerP: 'Whether you represent a government entity, enterprise, financial institution, or strategic partner, NEXGEN welcomes conversations that shape the future of renewable energy, digital transformation, and AI.',
      ctaTitle: 'Express Strategic Interest',
      ctaText: '',
      ctaLabel: 'Express Strategic Interest',
      ctaBand: false,
    },

    companies: {
      title: 'Ventures & Partnerships — NEXGEN Holdings',
      desc: 'NEXGEN Holdings’ ventures and partnerships across renewable & clean energy, digital transformation, and artificial intelligence: InPipe Energy, Esaal, SABY, Trust Flow, and Dari.',
      heroTitle: 'Ventures &amp; Partnerships',
      heroLead: 'NEXGEN’s ventures and partnerships, grouped by focus area: renewable &amp; clean energy, digital transformation, and artificial intelligence.',
      ctaTitle: 'Not sure which venture fits?',
      ctaText: 'Tell us what you are working on and we will point you to the right team.',
      ctaLabel: 'Contact Us',
    },

    inpipe: {
      title: 'InPipe Energy — HydroXS In-Pipe Hydropower | NEXGEN Holdings',
      desc: 'NEXGEN is the exclusive regional partner of InPipe Energy (USA), bringing HydroXS technology to the Gulf to turn excess water pressure into clean, reliable power.',
      heroEyebrow: 'Renewable &amp; Clean Energy',
      heroTitle: 'Turning Water Pressure Into Clean, Reliable Power',
      heroLead: 'NEXGEN is the exclusive regional partner bringing HydroXS® technology to the Gulf—enabling utilities, municipalities, and large facilities to recover energy, reduce emissions, and improve operational efficiency.',
      heroBtn: 'Contact Us',
      challengeH: 'The Challenge',
      challengeP1: 'Water delivery across the GCC consumes massive electricity. At pressure-control points, this energy is traditionally wasted as heat, driving up operating costs and carbon emissions.',
      challengeP2: 'Utilities need solutions that:',
      challengeList: [
        'Lower electricity consumption',
        'Reduce CO₂ emissions',
        'Improve pressure management',
        'Extend pipeline lifespan',
        'Require no operational disruption',
      ],
      solutionH: 'HydroXS Solution',
      solutionP: '<strong>HydroXS</strong> installs directly onto existing pipeline infrastructure and captures energy from excess pressure. As water flows through, the system safely reduces pressure while generating clean electricity.',
      advH: 'Key Advantages',
      advList: [
        'No change in water operations',
        'Predictable renewable power (day &amp; night)',
        'Works with gravity, pumping, regulator sites',
        'Supports national sustainability and Net Zero targets',
      ],
      specH: 'HydroXS Specifications',
      specList: [
        'Scalable from 10 kW to 2 MW',
        'Installs in pipe diameters of 4-110 inches <span class="nowrap">(5-280 cm)</span>',
        'Made in the USA',
        'Patent issued, with additional patents pending',
      ],
      resultsH: 'Real Results',
      resultsLead: 'Examples from existing deployments:',
      statsTop: [
        { v: '89,000<sup>+</sup>', l: 'Hours of fleet runtime' },
        { v: '99<sup>%</sup>', l: 'Fleet availability' },
        { v: '97.9<sup>%</sup>', l: 'Lowest per-site availability' },
        { v: '99.9<sup>%</sup>', l: 'Highest per-site availability' },
      ],
      cite: 'Source: InPipe Energy company profile, 2025.',
      useCasesH: 'GCC Use Cases',
      useCasesP: 'HydroXS is an ideal fit for:',
      useCasesList: [
        'Water transmission &amp; distribution',
        'District cooling lines',
        'Treated wastewater lines',
        'Firewater loops',
        'RO desalination networks',
        'High-pressure industrial water systems',
      ],
      processEyebrow: 'Delivery process',
      processH: 'NEXGEN Manages The Full Journey',
      steps: [
        'Data Collection Support',
        'Hydraulic &amp; Energy Analysis',
        'Technical &amp; Financial Proposal',
        'Procurement &amp; Installation',
        'Commissioning &amp; Monitoring',
      ],
      teamEyebrow: 'Our technology partner',
      teamH: 'The InPipe Energy Team',
      teamLead: 'The people behind HydroXS®, built on decades in water and clean energy.',
      ctaTitle: 'Bring HydroXS to your network.',
      ctaText: 'Get in touch to discuss whether HydroXS fits your site.',
      ctaLabel: 'Contact Us',
    },

    trustFlow: {
      title: 'Trust Flow — Corporate & Investor Onboarding AI | NEXGEN Holdings',
      desc: 'Trust Flow automates onboarding for banks, investment firms, funds, and asset managers with AI document extraction, automated KYC/KYB, and compliance workflows.',
      heroEyebrow: 'Artificial Intelligence',
      heroTitle: 'Trust Flow',
      heroLead: 'Intelligent onboarding for banks &amp; investment firms — a unified AI platform that accelerates onboarding, elevates compliance accuracy, and streamlines documentation for banks, corporate clients, investment firms, funds, and asset managers.',
      heroBtn: 'Contact Us',
      challengeH: 'The Challenge',
      challengeP: 'Financial institutions waste time and resources on:',
      challengeList: [
        'Manual document handling',
        'Repeated follow-ups',
        'Slow investor and corporate onboarding',
        'Fragmented compliance workflows',
        'High regulatory pressure',
        'Long turnaround times',
      ],
      challengeP2: 'These bottlenecks delay revenue, frustrate clients, and increase operational costs.',
      solutionH: 'The Solution',
      solutionP: '<strong>Trust Flow</strong> is a NEXGEN venture that automates the entire onboarding process with AI, ensuring fast, accurate, and complete files.',
      solutionP2: 'Every file arrives complete, sourced, and audit-ready—without an analyst retyping a single document.',
      includesH: 'What It Includes',
      includesList: [
        'AI document extraction',
        'Automated KYC/KYB',
        'Beneficial ownership mapping',
        'AML &amp; sanctions screening',
        'Risk scoring &amp; case summaries',
        'Digital submission &amp; electronic signatures',
        'Centralized analyst &amp; compliance workflows',
      ],
      servesH: 'Who It Serves',
      servesList: [
        'Banks',
        'Investment Firms &amp; Asset Managers',
        'Private Equity &amp; Venture Capital Funds',
        'Corporate Service Providers',
        'Real Estate Funds',
        'Family Offices',
      ],
      gainH: 'What Institutions Gain',
      gainList: [
        'Cost optimization',
        'Faster onboarding',
        'Higher compliance accuracy',
        'Better investor experience',
        'Standardized risk evaluation',
        'Reduced operational workload',
      ],
      ctaTitle: 'Learn More About Trust Flow',
      ctaText: 'Get in touch to learn more about Trust Flow for your bank, fund, or investment firm.',
      ctaLabel: 'Contact Us',
    },

    esaal: {
      title: 'Esaal — Digital Receipts & Spending Intelligence | NEXGEN Holdings',
      desc: 'In collaboration with Esaal, NEXGEN brings Plug-n-Play digital receipts to the GCC — real-time customer profiling, campaign measurement, and no extra hardware.',
      heroEyebrow: 'Digital Transformation',
      heroTitle: 'Esaal',
      heroLead: 'Digital receipts &amp; spending intelligence — in collaboration with Esaal, NEXGEN brings a Plug-n-Play digital receipt platform to the GCC, replacing paper receipts with real-time data.',
      heroBtn: 'Contact Us',
      heroBtn2: 'Visit esaal.co',
      introH: 'Digital Receipts &amp; Spending Intelligence',
      introLead: 'An AI engine that converts receipts into structured, searchable financial data—powering insights for individuals, businesses, and retailers. Esaal replaces the paper receipt with a smarter, digital one, and turns every transaction into a real-time customer signal.',
      problemH: 'The Problem',
      problemP: 'Businesses lose time and value to:',
      problemList: [
        'Lack of digitisation in invoicing processes',
        'Manual policy-compliance checks that consume staff time',
        'Customer profiling through data enrichment is very difficult',
        'Paper-receipt data that teams cannot put to use',
        'Limited tools for tax compliance and transparency in the UAE',
      ],
      problemStatV: '25<sup>%</sup>',
      problemStatP: 'Paper receipts leave 25% of businesses out of pocket by up to $10,000.',
      problemCite: 'Source: Esaal company profile.',
      solutionH: 'The Solution',
      solutionP: '<strong>Esaal</strong> turns every receipt—paper, email, POS—into clean, structured financial data instantly.',
      featuresH: 'Features',
      featuresList: [
        'AI receipt scanning',
        'Spending insights',
        'Business expense reporting',
        'Retail analytics',
        'Integrations with POS and ERP',
      ],
      platformEyebrow: 'The platform',
      platformH: 'Seamless Plug-n-Play With Your POS',
      cards: [
        { h: 'Plug-n-Play Integration', p: 'Smart receipts integrate directly with your POS and other tools. No additional apps or hardware required for you or your customers.' },
        { h: 'Real-Time Customer Profiling', p: 'Pinpoint your customers and their buying habits with advanced digital receipts, enhancing customer profiling and behavioral insights.' },
        { h: 'Campaign Measurement', p: 'Determine the effectiveness of your digital receipt campaigns through receipt-based measurement.' },
        { h: 'Connect', p: 'Link in-store transactions with a seamless plug-in, ensuring real-time data integration and accessibility.' },
        { h: 'Measure &amp; Optimise', p: 'Unlock comprehensive insights into your most valuable customers with the merchant dashboard, enabling targeted optimisation strategies.' },
        { h: 'Privacy &amp; Compliance', p: 'Customer data is handled with explicit opt-in at checkout, and the platform operates in line with applicable privacy and data-protection requirements.' },
      ],
      numbersEyebrow: 'By the numbers',
      numbersH: 'It works. We’ve got the receipts.',
      stats: [
        { v: 'More than 15,000', l: 'receipts' },
        { v: '30<sup>%</sup>', l: 'Opt-in rate for digital receipts at checkout' },
        { v: '70<sup>%</sup>', l: 'Open rates for our digital receipts' },
        { v: '20<sup>%</sup>', l: 'Click through rate on our digital receipts' },
      ],
      valueH: 'Value',
      valueList: [
        'Clear spending for individuals',
        'Accurate records for businesses',
        'Deep insights for retailers',
      ],
      appBtn: 'Get the App',
      caption: 'Esaal — the new, smarter way to E-receipt.',
      teamEyebrow: 'Our venture partner',
      teamH: 'The Esaal Team',
      teamLead: 'Esaal builds and runs the receipts platform. NEXGEN brings it to the Gulf.',
      advisorsTitle: 'Advisors',
      ctaTitle: 'Bring digital receipts to your customers.',
      ctaText: 'Talk to us about a Plug-n-Play rollout across your stores.',
      ctaLabel: 'Contact Us',
    },

    dari: {
      title: 'Dari — AI-Powered Smart Living System (In Development) | NEXGEN Holdings',
      desc: 'Dari is an in-development smart home and building platform that adapts to behavior, emotion, and daily routines using behavioral and emotional AI. Coming soon.',
      heroEyebrow: 'Artificial Intelligence',
      heroTitle: 'Dari',
      heroStatus: 'In development — coming soon',
      heroLead: 'AI Smart Living — a home and building ecosystem that understands behavior, emotion, and lifestyle.',
      heroBtn: 'Contact Us',
      introH: 'AI-Powered Smart Living System',
      introLead: 'Automation that anticipates the people in a building instead of reacting to the devices in it.',
      problemH: 'The Problem',
      problemP: 'Traditional smart home systems are device-based and reactive. They don’t understand people.',
      solutionH: 'The Solution',
      solutionP: '<strong>Dari</strong> creates human-centric automation using behavioral and emotional AI.',
      featuresH: 'Features',
      featuresList: [
        'Behavioral learning',
        'Emotion-aware automation',
        'Unified IoT control',
        'Smart building mode',
        'Energy optimization',
      ],
      valueH: 'Value',
      values: ['Energy efficiency', 'Comfort', 'Safety', 'Premium living experience'],
      ctaTitle: 'Shape the next generation of smart living.',
      ctaText: 'Explore a partnership around Dari.',
      ctaLabel: 'Contact Us',
    },

    saby: {
      title: 'SABY — Modern Technology Studio | NEXGEN Holdings',
      desc: 'SABY is NEXGEN’s dedicated software engineering studio delivering AI development, digital transformation, and enterprise-grade platforms for the region.',
      heroEyebrow: 'Digital Transformation',
      heroTitle: 'SABY',
      heroLead: 'Modern technology studio — software engineering, AI development, digital transformation, and enterprise platforms.',
      heroBtn: 'Contact Us',
      whoH: 'Who We Are',
      whoP: 'SABY is NEXGEN’s technology subsidiary, delivering modern, scalable digital solutions for the region.',
      expertiseH: 'Expertise',
      expertiseList: [
        'AI &amp; automation',
        'Web &amp; mobile apps',
        'SaaS engineering',
        'Cloud &amp; cybersecurity',
        'UX/UI',
        'Enterprise integrations',
      ],
      whyH: 'Why SABY?',
      whyCards: ['Modern engineering practices', 'Fast delivery cycles', 'Enterprise-grade execution'],
      ctaTitle: 'Have something to build?',
      ctaText: 'Talk to our engineering studio about AI and digital transformation.',
      ctaLabel: 'Contact Us',
    },

    contact: {
      title: 'Contact Us — NEXGEN Holdings',
      desc: 'Contact NEXGEN Holdings for partnerships, ventures, and site assessments. Phone +973 3660 0911, email info@nexgen.bh.',
      heroTitle: 'Contact Us',
      heroLead: 'Whether you represent a government entity, enterprise, financial institution, or strategic partner, NEXGEN welcomes conversations that shape the future of renewable energy, digital transformation, and AI.',
      eyebrow: 'Direct lines',
      h2: 'Talk to NEXGEN',
      phoneLabel: 'Phone',
      phoneNote: 'Call us for partnerships, ventures, and general inquiries.',
      emailLabel: 'Email',
      emailNote: 'Organizations interested in exploring strategic alignment with NEXGEN are invited to submit a confidential inquiry.',
      linkedinLabel: 'LinkedIn',
      linkedinNote: 'Follow NEXGEN Holdings for venture and partnership updates.',
      focusEyebrow: 'Our focus',
      focusH: 'Where We Work',
      focusLead: 'Talk to us about any of NEXGEN’s three focus areas.',
      cardEnergyH: 'Renewable &amp; Clean Energy',
      cardEnergyP: 'HydroXS in-pipe hydropower with InPipe Energy (USA) for utilities, municipalities, and large facilities.',
      cardDigitalH: 'Digital Transformation',
      cardDigitalP: 'Digital receipts and connected platforms, and an engineering studio to build them.',
      cardAiH: 'Artificial Intelligence',
      cardAiP: 'AI for institutional onboarding and compliance, and for homes that understand their people.',
    },
  },

  people: {
    omar: { role: 'Head Of Fintech', note: 'Oversees NEXGEN’s financial technology portfolio, including digital onboarding platforms, compliance solutions, and financial infrastructure serving banks, investment firms, and enterprises.' },
    jernej: { role: 'Head Of Renewable Energy', note: 'Leads NEXGEN’s renewable energy initiatives, overseeing decarbonization projects, water-energy recovery solutions, and strategic partnerships with utilities and infrastructure operators across the GCC.' },
    moatassem: { role: 'Head of AI &amp; Digital Transformation', note: 'Leads NEXGEN’s artificial intelligence and digital transformation agenda.' },
    abdullah: { alt: 'Abdullah Sultan AlMutairi, Chairman &amp; CEO of NEXGEN Holdings' },
    advisorAlenezi: { role: 'Shadow Executive · C-Suite Advisory' },
    advisorAlsharah: { role: 'Founder and CEO of Innotech' },
  },

  inpipeTeamRoles: {
    'Gregg Semler': 'CEO &amp; Founder',
    'David Frost': 'Business Development',
    'Richard Klann': 'Vice President, Finance',
    'Mickey Conner': 'Director, Engineering',
    'John Robinson': 'Operations Manager',
    'Kyle Perrin': 'Sales Manager',
    'Chris Morrison': 'Industry Advisor · Morrison Water',
    'Mary Ann Dickinson': 'Industry Advisor · Alliance for Water Efficiency',
  },

  esaalTeamRoles: {
    'Reem Musabbah': 'CEO &amp; Founder',
    'AlHassan Faraj Allah': 'CTO',
    'Anas Ali': 'COO &amp; Co-founder',
  },

  esaalAdvisorRoles: {
    'Mohamed Roushdy, MBA': 'Fintech · Open Banking · Digital Transformation',
    'Sreela Sreenarayanan': 'Commercial Operations · Pricing &amp; Financials',
    'Ashutosh Ashish': 'Digital Banking · Onboarding · Digital Channels',
  },

  inpipeSites: [
    { v: '30 kW', n: 'Hillsboro Water, Oregon', d: 'About 200,000 kWh per year<br>1,400 tons CO₂ offset<br>Commissioned September 2020', extra: 'Output net-metered, used for stadium lighting, EV charging and concessions.' },
    { v: '22 kW', n: 'Skagit PUD pumping facility', d: 'About 104,000 kWh per year<br>728 tons CO₂ offset over its lifetime<br>Commissioned July 2021', extra: '' },
    { v: '30 kW', n: 'EBMUD (East Bay Municipal Utility District) pump facility', d: '150,000 kWh per year<br>1,050 tons CO₂ offset<br>Commissioned September 2023', extra: 'InPipe owns, operates and maintains the structure.' },
    { v: '56 kW', n: 'Aurora Water regulator replacement', d: '255,000 kWh per year<br>3,023 tons CO₂ offset<br>Commissioned October 2024', extra: '' },
  ],

  /* Alt text for decorative/supporting imagery, kept out of the page templates
     so each locale can word it naturally. */
  imgAlts: {
    corporateVisual: 'NEXGEN Holdings corporate visual',
    inpipeVisual: 'Water infrastructure energy recovery',
    inpipePlant: 'HydroXS installed on a water pipeline',
    esaalMark: 'Esaal app icon',
  },

  jsonld: {
    name: 'NEXGEN Holdings',
    description: 'NEXGEN Holdings is a Gulf-based holding company building high-impact ventures in renewable and clean energy, digital transformation, and artificial intelligence.',
  },
};
